// UI-backend glue generation (see lidl_gen_ui.h).
//
// The authoring split for type=ui_qml + interface=universal:
//
//   USER-WRITTEN   the .rep (the view contract — full QtRO power: SLOTs,
//                  PROPs, SIGNALs) and the *Backend.{h,cpp} class deriving
//                  the repc <RepClass>SimpleSource + LogosUiPluginContext
//                  (which supplies onContextReady() and the modules() typed
//                  accessors to declared dependencies — a UI plugin is a view,
//                  not a module, so it gets nothing else: no modulePath/
//                  instanceId/persistence, no events of its own). The deps'
//                  wrappers are Qt-typed (api-style qt), matching the .rep slots.
//
//   GENERATED      <name>_ui_interface.h (the *Interface: PluginInterface +
//                  IID) and <name>_ui_glue.{h,cpp} (the *Plugin:
//                  Q_PLUGIN_METADATA, name()/version(),
//                  ViewPluginBase, and the Q_INVOKABLE initLogos that
//                  constructs LogosModules, wires it into the backend —
//                  firing onContextReady — and registers the backend as the
//                  QtRO source).
//
// Existing LogosAPI*-based UI plugins (interface: legacy) are untouched.

#include "lidl_gen_ui.h"

#include <QFile>
#include <QRegularExpression>
#include <QTextStream>

bool lidlUiParseRepClass(const QString& repPath, QString* repClass, QString* whyNot)
{
    QFile f(repPath);
    if (!f.open(QIODevice::ReadOnly | QIODevice::Text)) {
        if (whyNot) *whyNot = "cannot read .rep file: " + repPath;
        return false;
    }
    const QString text = QString::fromUtf8(f.readAll());
    // Same extraction logos_module(REP_FILE ...) performs: the first class
    // declaration names the QtRO types (SimpleSource/Replica/ViewPluginBase).
    QRegularExpressionMatch m =
        QRegularExpression(QStringLiteral("class[ \\t]+([A-Za-z_][A-Za-z0-9_]*)")).match(text);
    if (!m.hasMatch()) {
        if (whyNot) *whyNot = "no `class <Name>` declaration found in " + repPath;
        return false;
    }
    if (repClass) *repClass = m.captured(1);
    return true;
}

QString lidlMakeUiInterfaceHeader(const UiGlueSpec& spec)
{
    QString h;
    QTextStream s(&h);
    s << "// AUTO-GENERATED by logos-view-generator --backend ui -- do not edit\n";
    s << "#pragma once\n\n";
    s << "#include \"interface.h\"\n\n";
    s << "class " << spec.pluginBase << "Interface : public PluginInterface\n{\npublic:\n";
    s << "    virtual ~" << spec.pluginBase << "Interface() = default;\n};\n\n";
    s << "#define " << spec.pluginBase << "Interface_iid \"org.logos." << spec.pluginBase << "Interface\"\n";
    s << "Q_DECLARE_INTERFACE(" << spec.pluginBase << "Interface, " << spec.pluginBase << "Interface_iid)\n";
    return h;
}

QString lidlMakeUiGlueHeader(const UiGlueSpec& spec)
{
    QString h;
    QTextStream s(&h);
    s << "// AUTO-GENERATED by logos-view-generator --backend ui -- do not edit\n";
    s << "#pragma once\n\n";
    s << "#include <QObject>\n#include <QString>\n#include <memory>\n\n";
    s << "#include \"" << spec.backendHeader << "\"\n";
    s << "#include \"" << spec.moduleName << "_ui_interface.h\"\n";
    s << "#include \"LogosViewPluginBase.h\"\n\n";
    s << "class LogosAPI;\nstruct LogosModules;\n\n";
    s << "// Generated UI plugin around the user-written " << spec.backendClass << ".\n";
    s << "// Owns the backend, wires the LogosModules typed-deps aggregate into it\n";
    s << "// on initLogos (firing onContextReady — so dependency subscriptions are\n";
    s << "// live before the view's first call), and registers it as the QtRO\n";
    s << "// source for the QML replica.\n";
    s << "class " << spec.pluginBase << "Plugin : public QObject,\n";
    s << QString(" ").repeated(22 + spec.pluginBase.size()) << "public " << spec.pluginBase << "Interface,\n";
    s << QString(" ").repeated(22 + spec.pluginBase.size()) << "public " << spec.repClass << "ViewPluginBase\n{\n";
    s << "    Q_OBJECT\n";
    s << "    Q_PLUGIN_METADATA(IID " << spec.pluginBase << "Interface_iid FILE \"metadata.json\")\n";
    s << "    Q_INTERFACES(" << spec.pluginBase << "Interface LogosViewPlugin)\n\npublic:\n";
    s << "    // Ctor/dtor are out-of-line: this header is compiled by moc TUs\n";
    s << "    // where LogosModules may be incomplete.\n";
    s << "    explicit " << spec.pluginBase << "Plugin(QObject* parent = nullptr);\n";
    s << "    ~" << spec.pluginBase << "Plugin() override;\n\n";
    s << "    QString name() const override { return QStringLiteral(\"" << spec.moduleName << "\"); }\n";
    s << "    QString version() const override { return QStringLiteral(\"" << spec.moduleVersion << "\"); }\n\n";
    s << "    Q_INVOKABLE void initLogos(LogosAPI* api);\n\n";
    // Teardown, reached by the host through the META-OBJECT rather than the
    // vtable. PluginInterface is compiled separately into every plugin, so
    // adding a virtual there would shift the vtable under every plugin already
    // built and turn a missing hook into undefined behaviour instead of a
    // no-op. `initLogos` above is delivered by name for the same reason.
    //
    // Emitted unconditionally, for EVERY view. A backend that does not derive
    // LogosUiPluginContext answers Synchronous through the SFINAE helper, so
    // the surface costs a view that ignores it exactly one meta-call at
    // teardown -- and emitting it always is what lets ui-host resolve one name
    // rather than probing for two shapes.
    //
    // Returns the LogosShutdown as an int because the host resolves this by
    // signature string and must not need the SDK enum to do it.
    s << "    Q_INVOKABLE int aboutToUnload();\n\n";
    s << "Q_SIGNALS:\n";
    s << "    // Emitted when an Asynchronous teardown has finished. The host\n";
    s << "    // connects to this by name and stops waiting on the first one.\n";
    s << "    void unloadFinished();\n\n";
    s << "private:\n";
    // DECLARATION ORDER IS THE CONTRACT. Members are destroyed in reverse
    // declaration order, so the typed-deps aggregate is declared FIRST in
    // order to be destroyed LAST -- after the backend that reaches its
    // dependencies through it.
    //
    // A view backend is entitled to call modules() from its destructor: it is
    // the only door it has to its dependencies, and teardown is exactly when a
    // view wants to use it. Emitted the other way round, that read lands in
    // freed memory and NOTHING says so -- isContextReady() keeps answering
    // true, because the pointer LogosUiPluginContext holds is never cleared,
    // so the call goes out and comes back wrong instead of crashing. That is
    // what made a chat_ui teardown report "consumer wrapper has no transport
    // (null bridge)" rather than fault.
    //
    // Pinned twice, because a comment does not survive an editor: the
    // `view-generator` check greps the two lines' order, and
    // `ui-plugin-metaobject` destroys a real compiled plugin and asks its
    // backend what it saw.
    s << "    // Declared FIRST so it is destroyed LAST: the backend below may\n";
    s << "    // reach its dependencies through modules() from its destructor.\n";
    s << "    std::unique_ptr<LogosModules> m_logosModules;\n";
    s << "    std::unique_ptr<" << spec.backendClass << "> m_backend;\n";
    s << "};\n";
    return h;
}

QString lidlMakeUiGlueSource(const UiGlueSpec& spec)
{
    QString c;
    QTextStream s(&c);
    s << "// AUTO-GENERATED by logos-view-generator --backend ui -- do not edit\n";
    s << "#include \"" << spec.moduleName << "_ui_glue.h\"\n\n";
    s << "#include \"logos_api.h\"\n";
    s << "#include \"logos_ui_plugin_context.h\"\n";
    s << "#include \"logos_sdk.h\"\n\n";
    s << spec.pluginBase << "Plugin::" << spec.pluginBase << "Plugin(QObject* parent)\n";
    s << "    : QObject(parent)\n";
    s << "    , m_backend(std::make_unique<" << spec.backendClass << ">())\n";
    s << "{\n}\n\n";
    s << spec.pluginBase << "Plugin::~" << spec.pluginBase << "Plugin() = default;\n\n";
    s << "void " << spec.pluginBase << "Plugin::initLogos(LogosAPI* api)\n{\n";
    s << "    if (m_logosModules || !api) return;\n";
    s << "    // Construct the typed-deps aggregate and wire it into the backend.\n";
    s << "    // maybeSetUiPluginModules fires onContextReady once modules() is live,\n";
    s << "    // so the backend can make typed calls and subscribe to dependency\n";
    s << "    // events from the hook. A UI plugin is a view, not a module — it has\n";
    s << "    // no host identity (modulePath/instanceId/persistence) to wire. The\n";
    s << "    // SFINAE helper no-ops if the backend doesn't derive LogosUiPluginContext.\n";
    s << "    m_logosModules = std::make_unique<LogosModules>(api);\n";
    s << "    _logos_codegen_::maybeSetUiPluginModules(*m_backend, m_logosModules.get());\n";
    s << "    // Register the backend (a " << spec.repClass << "SimpleSource) as the QtRO\n";
    s << "    // source so ui-host can enableRemoting the typed " << spec.repClass << "SourceAPI.\n";
    s << "    setBackend(m_backend.get());\n";
    s << "}\n\n";
    // Teardown. The plugin object is what the host reaches by name; the work
    // itself belongs to the user-written backend.
    s << "int " << spec.pluginBase << "Plugin::aboutToUnload()\n{\n";
    s << "    // maybeUiPluginAboutToUnload installs the completion trampoline\n";
    s << "    // BEFORE asking the backend, because a backend that finishes inline\n";
    s << "    // would otherwise signal into an empty slot and the host would wait\n";
    s << "    // out the whole grace period for a view already done.\n";
    s << "    //\n";
    s << "    // The trampoline runs on whichever thread the backend finished on, so\n";
    s << "    // it must not touch the plugin directly -- a QUEUED invokeMethod\n";
    s << "    // marshals the emission back to the plugin's thread, which is where\n";
    s << "    // the host is waiting. It answers 0 (Synchronous) for a backend that\n";
    s << "    // does not derive LogosUiPluginContext.\n";
    s << "    return _logos_codegen_::maybeUiPluginAboutToUnload(*m_backend, [this]() {\n";
    s << "        QMetaObject::invokeMethod(this, \"unloadFinished\", Qt::QueuedConnection);\n";
    s << "    });\n";
    s << "}\n";
    return c;
}
